[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "arXiv_classification"
authors = [{name = "Aurora Mugnai e Chiara Tocchini"}]
dynamic = ["version", "description"]
