name: Sphinx to GitHub Pages
  # You may pin to the exact commit or the version.
  # uses: sphinx-notes/pages@3a7b173ecba074b270b37c64007c1edfd8465892
  uses: sphinx-notes/pages@3.1
  with:
    # Path to Sphinx source files
    documentation_path: ./docs # optional, default is ./docs
    # Path to requirements file, used in `pip install -r XXX` command
    requirements_path: ./docs/requirements.txt # optional, default is ./docs/requirements.txt
    # Extras of Requirement Specifier, used in `pip install .[XXX]` command
    pyproject_extras: docs # optional, default is docs
    # Version of Python
    python_version: 3.10 # optional, default is 3.10
    # Version of Sphinx
    sphinx_version: 7.3.7  # optional, default is 
    # Enable cache to speed up documentation building
    cache: # optional
    # Additional options passed to sphinx-build
    sphinx_build_options: make html # optional, default is 
    # Whether to automatically checkout the repository, if false, user need to do it byself
    checkout: # optional, default is true
    # Whether to automatically publish the pages, if false, user need to manually publish by self
    publish: # optional, default is true
          
