name: Unit tests

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          # python -m pip install spacy
          # python -m spacy download en_core_web_md
          # python -m pip install pandas
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest
